import { fontFamily } from './fontFamily';
import { fontSize } from './fontSize';
import { fontStyle } from './fontStyle';
import { fontWeight } from './fontWeight';

export const typography = {
  heading: {
    heading0: {
      fontFamily: fontFamily.poppinsRegular,
      fontSize: fontSize.s14,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w400,
      lineHeight: fontSize.s20,
      textTransform: 'uppercase',
    },
    heading1: {
      fontFamily: fontFamily.bauhausStdMedium,
      fontSize: fontSize.s44,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w500,
      lineHeight: fontSize.s52,
      letterSpacing: -0.8,
    },
    heading2: {
      fontFamily: fontFamily.bauhausStdMedium,
      fontSize: fontSize.s40,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w500,
      lineHeight: fontSize.s48,
      letterSpacing: -0.8,
    },
    heading3: {
      fontFamily: fontFamily.bauhausStdMedium,
      fontSize: fontSize.s32,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w500,
      lineHeight: fontSize.s44,
      letterSpacing: -0.8,
      textShadowOffset: { width: 2, height: 2 },
      textShadowRadius: 16,
      textShadowColor: 'rgba(0, 0, 0, 0.25)',
    },
    heading4: {
      fontFamily: fontFamily.bauhausStdMedium,
      fontSize: fontSize.s24,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w500,
      lineHeight: fontSize.s32,
      letterSpacing: -0.6,
    },
    heading5: {
      fontFamily: fontFamily.bauhausStdMedium,
      fontSize: fontSize.s20,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w500,
      lineHeight: fontSize.s24,
      letterSpacing: -0.6,
    },
    heading6: {
      fontFamily: fontFamily.poppinsMedium,
      fontSize: fontSize.s24,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w500,
      lineHeight: fontSize.s36,
    },
    heading7: {
      fontFamily: fontFamily.poppinsSemiBold,
      fontSize: fontSize.s24,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w600,
      lineHeight: fontSize.s36,
    },
    heading8: {
      fontFamily: fontFamily.bauhausStdMedium,
      fontSize: fontSize.s16,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w500,
      lineHeight: fontSize.s20,
    },
  },
  subHeading: {
    subHeading1: {
      fontFamily: fontFamily.poppinsRegular,
      fontSize: fontSize.s20,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w400,
      lineHeight: fontSize.s32,
    },
    subHeading2: {
      fontFamily: fontFamily.poppinsMedium,
      fontSize: fontSize.s20,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w500,
      lineHeight: fontSize.s32,
    },
    subHeading3: {
      fontFamily: fontFamily.poppinsSemiBold,
      fontSize: fontSize.s20,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w600,
      lineHeight: fontSize.s32,
    },
    subHeading4: {
      fontFamily: fontFamily.bauhausStdMedium,
      fontSize: fontSize.s18,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w500,
      lineHeight: fontSize.s24,
      letterSpacing: -0.4,
    },
    subHeading5: {
      fontFamily: fontFamily.bauhausStdMedium,
      fontSize: fontSize.s16,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w500,
      lineHeight: fontSize.s20,
      letterSpacing: -0.4,
    },
    subHeading6: {
      fontFamily: fontFamily.poppinsMedium,
      fontSize: fontSize.s16,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w500,
      lineHeight: fontSize.s24,
    },
    subHeading7: {
      fontFamily: fontFamily.poppinsRegular,
      fontSize: fontSize.s16,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w600,
      lineHeight: fontSize.s24,
    },
    subHeading8: {
      fontFamily: fontFamily.poppinsSemiBold,
      fontSize: fontSize.s14,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w600,
      lineHeight: fontSize.s20,
    },
  },
  button: {
    fontFamily: fontFamily.poppinsMedium,
    fontSize: fontSize.s14,
    fontStyle: fontStyle.normal,
    fontWeight: fontWeight.w500,
    lineHeight: fontSize.s20,
  },
  link: {
    fontFamily: fontFamily.poppinsMedium,
    fontSize: fontSize.s14,
    fontStyle: fontStyle.normal,
    fontWeight: fontWeight.w500,
    lineHeight: fontSize.s20,
    textDecorationLine: 'underline',
    textTransform: 'uppercase',
  },
  linkSmall: {
    fontFamily: fontFamily.poppinsRegular,
    fontSize: fontSize.s12,
    fontStyle: fontStyle.normal,
    fontWeight: fontWeight.w500,
    lineHeight: fontSize.s18,
    textDecorationLine: 'underline',
    textTransform: 'capitalize',
  },
  bodyLarge: {
    regular: {
      fontFamily: fontFamily.poppinsRegular,
      fontSize: fontSize.s16,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w400,
      lineHeight: fontSize.s24,
    },
    medium: {
      fontFamily: fontFamily.poppinsMedium,
      fontSize: fontSize.s16,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w500,
      lineHeight: fontSize.s24,
    },
    light: {
      fontFamily: fontFamily.poppinsLight,
      fontSize: fontSize.s16,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w300,
      lineHeight: fontSize.s24,
    },
  },
  bodyMedium: {
    regular: {
      fontFamily: fontFamily.poppinsRegular,
      fontSize: fontSize.s14,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w400,
      lineHeight: fontSize.s20,
    },
    medium: {
      fontFamily: fontFamily.poppinsMedium,
      fontSize: fontSize.s14,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w500,
      lineHeight: fontSize.s20,
    },
    light: {
      fontFamily: fontFamily.poppinsLight,
      fontSize: fontSize.s14,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w300,
      lineHeight: fontSize.s20,
    },
  },
  bodySmall: {
    regular: {
      fontFamily: fontFamily.poppinsRegular,
      fontSize: fontSize.s12,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w400,
      lineHeight: fontSize.s18,
    },
    medium: {
      fontFamily: fontFamily.poppinsMedium,
      fontSize: fontSize.s12,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w500,
      lineHeight: fontSize.s18,
    },
    light: {
      fontFamily: fontFamily.poppinsLight,
      fontSize: fontSize.s12,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w300,
      lineHeight: fontSize.s18,
    },
  },
  bodyExtraSmall: {
    regular: {
      fontFamily: fontFamily.poppinsRegular,
      fontSize: fontSize.s10,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w400,
      lineHeight: fontSize.s16,
    },
  },
  tags: {
    small: {
      fontFamily: fontFamily.poppinsMedium,
      fontSize: fontSize.s10,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w500,
      lineHeight: fontSize.s16,
    },
    medium: {
      fontFamily: fontFamily.poppinsMedium,
      fontSize: fontSize.s12,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w500,
      lineHeight: fontSize.s18,
    },
  },
  price: {
    regularStroked: {
      fontFamily: fontFamily.poppinsRegular,
      fontSize: fontSize.s12,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w400,
      lineHeight: fontSize.s18,
    },
    mediumStroked: {
      fontFamily: fontFamily.poppinsRegular,
      fontSize: fontSize.s14,
      fontStyle: fontStyle.normal,
      fontWeight: fontWeight.w500,
      lineHeight: fontSize.s20,
    },
  },
  placeholderLables: {
    fontFamily: fontFamily.poppinsLight,
    fontSize: fontSize.s14,
    fontStyle: fontStyle.normal,
    fontWeight: fontWeight.w300,
    lineHeight: fontSize.s20,
  },
};
