/**
 * Asset Mapping Script
 * Automatically maps all images and icons in the assets folder
 * Run: node scripts/mapAssets.js
 */

const fs = require('fs');
const path = require('path');

const assetsDir = path.join(__dirname, '../assets');
const assetsIndexPath = path.join(__dirname, '../src/assets/index.ts');

// Supported image formats
const imageExtensions = ['.png', '.jpg', '.jpeg', '.svg', '.webp'];

/**
 * Convert filename to camelCase
 */
function toCamelCase(str) {
  return str
    .replace(/[-_](.)/g, (_, char) => char.toUpperCase())
    .replace(/^./, char => char.toLowerCase());
}

/**
 * Get all image files from a directory
 */
function getImageFiles(dir, baseDir = dir) {
  const files = [];
  const items = fs.readdirSync(dir);

  items.forEach(item => {
    const fullPath = path.join(dir, item);
    const stat = fs.statSync(fullPath);

    if (stat.isDirectory()) {
      files.push(...getImageFiles(fullPath, baseDir));
    } else {
      const ext = path.extname(item).toLowerCase();
      if (imageExtensions.includes(ext)) {
        const relativePath = path.relative(baseDir, fullPath);
        files.push({
          name: path.basename(item, ext),
          path: relativePath,
          fullPath: fullPath,
          ext: ext,
        });
      }
    }
  });

  return files;
}

/**
 * Generate assets index content
 */
function generateAssetsIndex() {
  const imagesDir = path.join(assetsDir, 'images');
  const iconsDir = path.join(assetsDir, 'icons');

  const images = fs.existsSync(imagesDir) ? getImageFiles(imagesDir, assetsDir) : [];
  const icons = fs.existsSync(iconsDir) ? getImageFiles(iconsDir, assetsDir) : [];

  // Check root assets folder for app_icons.jpg
  const rootFiles = fs.readdirSync(assetsDir).filter(file => {
    const ext = path.extname(file).toLowerCase();
    return imageExtensions.includes(ext);
  });

  let content = `/**
 * Assets Index
 * Centralized asset management for the application
 * 
 * This file provides easy access to all assets (fonts, images, icons, etc.)
 * throughout the application.
 * 
 * Auto-generated by scripts/mapAssets.js
 * Last updated: ${new Date().toISOString()}
 */

// Font assets
export const fonts = {
  // Poppins Font Family
  poppins: {
    black: require('../../assets/fonts/Poppins-Black.ttf'),
    blackItalic: require('../../assets/fonts/Poppins-BlackItalic.ttf'),
    bold: require('../../assets/fonts/Poppins-Bold.ttf'),
    boldItalic: require('../../assets/fonts/Poppins-BoldItalic.ttf'),
    extraBold: require('../../assets/fonts/Poppins-ExtraBold.ttf'),
    extraBoldItalic: require('../../assets/fonts/Poppins-ExtraBoldItalic.ttf'),
    extraLight: require('../../assets/fonts/Poppins-ExtraLight.ttf'),
    extraLightItalic: require('../../assets/fonts/Poppins-ExtraLightItalic.ttf'),
    italic: require('../../assets/fonts/Poppins-Italic.ttf'),
    light: require('../../assets/fonts/Poppins-Light.ttf'),
    lightItalic: require('../../assets/fonts/Poppins-LightItalic.ttf'),
    medium: require('../../assets/fonts/Poppins-Medium.ttf'),
    mediumItalic: require('../../assets/fonts/Poppins-MediumItalic.ttf'),
    regular: require('../../assets/fonts/Poppins-Regular.ttf'),
    semiBold: require('../../assets/fonts/Poppins-SemiBold.ttf'),
    semiBoldItalic: require('../../assets/fonts/Poppins-SemiBoldItalic.ttf'),
    thin: require('../../assets/fonts/Poppins-Thin.ttf'),
    thinItalic: require('../../assets/fonts/Poppins-ThinItalic.ttf'),
  },
  // Bauhaus Font Family
  bauhaus: {
    bold: require('../../assets/fonts/BauhausStd-Bold.ttf'),
    demi: require('../../assets/fonts/BauhausStd-Demi.ttf'),
    heavy: require('../../assets/fonts/BauhausStd-Heavy.ttf'),
    light: require('../../assets/fonts/BauhausStd-Light.ttf'),
    medium: require('../../assets/fonts/BauhausStd-Medium.ttf'),
  },
  // Icon Font
  icomoon: require('../../assets/fonts/icomoon.ttf'),
};

// Image assets
export const images = {
`;

  // Add images
  if (images.length > 0) {
    images.forEach(img => {
      const varName = toCamelCase(img.name);
      const requirePath = `../../assets/${img.path.replace(/\\/g, '/')}`;
      content += `  ${varName}: require('${requirePath}'),\n`;
    });
  } else {
    content += `  // No images found. Add images to assets/images/ folder\n`;
  }

  content += `};

// Icon assets
export const icons = {
`;

  // Add icons
  if (icons.length > 0) {
    icons.forEach(icon => {
      const varName = toCamelCase(icon.name);
      const requirePath = `../../assets/${icon.path.replace(/\\/g, '/')}`;
      content += `  ${varName}: require('${requirePath}'),\n`;
    });
  } else {
    content += `  // No icons found. Add icons to assets/icons/ folder\n`;
  }

  // Add app_icons if found in root
  const appIcon = rootFiles.find(f => f.toLowerCase().includes('app_icon'));
  if (appIcon) {
    const varName = 'appIcon';
    content += `  ${varName}: require('../../assets/${appIcon}'),\n`;
  }

  content += `};

// Export all assets
const assets = {
  fonts,
  images,
  icons,
};

export default assets;
`;

  return content;
}

/**
 * Main function
 */
function main() {
  try {
    console.log('Mapping assets...');
    
    const content = generateAssetsIndex();
    fs.writeFileSync(assetsIndexPath, content, 'utf8');
    
    console.log('✅ Assets index updated successfully!');
    console.log(`📁 Updated: ${assetsIndexPath}`);
  } catch (error) {
    console.error('❌ Error mapping assets:', error);
    process.exit(1);
  }
}

if (require.main === module) {
  main();
}

module.exports = { generateAssetsIndex, toCamelCase };

