/**
 * Assets Index
 * Centralized asset management for the application
 * 
 * This file provides easy access to all assets (fonts, images, icons, etc.)
 * throughout the application.
 * 
 * Auto-generated by scripts/mapAssets.js
 * Last updated: 2025-12-14T05:52:56.608Z
 */

// Font assets
export const fonts = {
  // Poppins Font Family
  poppins: {
    black: require('../../assets/fonts/Poppins-Black.ttf'),
    blackItalic: require('../../assets/fonts/Poppins-BlackItalic.ttf'),
    bold: require('../../assets/fonts/Poppins-Bold.ttf'),
    boldItalic: require('../../assets/fonts/Poppins-BoldItalic.ttf'),
    extraBold: require('../../assets/fonts/Poppins-ExtraBold.ttf'),
    extraBoldItalic: require('../../assets/fonts/Poppins-ExtraBoldItalic.ttf'),
    extraLight: require('../../assets/fonts/Poppins-ExtraLight.ttf'),
    extraLightItalic: require('../../assets/fonts/Poppins-ExtraLightItalic.ttf'),
    italic: require('../../assets/fonts/Poppins-Italic.ttf'),
    light: require('../../assets/fonts/Poppins-Light.ttf'),
    lightItalic: require('../../assets/fonts/Poppins-LightItalic.ttf'),
    medium: require('../../assets/fonts/Poppins-Medium.ttf'),
    mediumItalic: require('../../assets/fonts/Poppins-MediumItalic.ttf'),
    regular: require('../../assets/fonts/Poppins-Regular.ttf'),
    semiBold: require('../../assets/fonts/Poppins-SemiBold.ttf'),
    semiBoldItalic: require('../../assets/fonts/Poppins-SemiBoldItalic.ttf'),
    thin: require('../../assets/fonts/Poppins-Thin.ttf'),
    thinItalic: require('../../assets/fonts/Poppins-ThinItalic.ttf'),
  },
  // Bauhaus Font Family
  bauhaus: {
    bold: require('../../assets/fonts/BauhausStd-Bold.ttf'),
    demi: require('../../assets/fonts/BauhausStd-Demi.ttf'),
    heavy: require('../../assets/fonts/BauhausStd-Heavy.ttf'),
    light: require('../../assets/fonts/BauhausStd-Light.ttf'),
    medium: require('../../assets/fonts/BauhausStd-Medium.ttf'),
  },
  // Icon Font
  icomoon: require('../../assets/fonts/icomoon.ttf'),
};

// Image assets
export const images = {
  // No images found. Add images to assets/images/ folder
};

// Icon assets
export const icons = {
  // No icons found. Add icons to assets/icons/ folder
};

// Export all assets
const assets = {
  fonts,
  images,
  icons,
};

export default assets;
